In [11]:
import numpy as np
import pandas as pd

In [12]:
matrix = np.zeros((11, 17))
matrix[0, 0] = 1
matrix[1, 1] = 1
matrix[6, 2] = 1
matrix[9, 3] = 1
matrix[7, 4] = -1
matrix[8, 5] = -1
matrix[10, 6] = 1

matrix[0, 7] = -1
matrix[5, 7] = 1

matrix[1, 8] = -1
matrix[4, 8] = 1
matrix[5, 8] = -1

matrix[3, 9] = 1
matrix[4, 9] = -1

matrix[2, 10] = 1
matrix[3, 10] = -1

matrix[1, 11] = 1
matrix[2, 11] = -1

matrix[0, 12] = 1
matrix[1, 12] = -1

matrix[0, 13] = -1
matrix[6, 13] = -1
matrix[7, 13] = 1
matrix[8, 13] = 1

matrix[6, 14] = -1
matrix[8, 14] = 1
matrix[9, 14] = 1
matrix[10, 14] = -1

matrix[9, 15] = -1
matrix[10, 15] = 1

matrix[1, 16] = -1
matrix[4, 16] = 1
matrix[8, 16] = -1
matrix[10, 16] = 1

print(matrix)

[[ 1.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0. -1.  0.  0.  1. -1.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1. -1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0. -1.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0. -1.  1.  1.]]


In [13]:
from scipy.linalg import null_space

# Compute the left null space of the stoichiometry matrix
left_null_space = null_space(matrix.T)

# Check if the left null space is non-empty
if left_null_space.size == 0:
    print("There is no left nullspace.")
else:
    print("There is a left nullspace.")
    print("Left nullspace basis vectors:")
    print(left_null_space)

There is no left nullspace.


(b). 

In [17]:
# Concatenate the matrix with its negative
reversible_matrix = np.concatenate((matrix, -matrix), axis=1)

print(reversible_matrix)
print(reversible_matrix.shape)  # Should be (11, 34)

[[ 1.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  1. -1.  0.  0.  0. -1.
  -0. -0. -0. -0. -0. -0.  1. -0. -0. -0. -0. -1.  1. -0. -0. -0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0. -1.  0.  0.  1. -1.  0.  0.  0. -1. -0.
  -1. -0. -0. -0. -0. -0. -0.  1. -0. -0. -1.  1. -0. -0. -0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0. -0.
  -0. -0. -0. -0. -0. -0. -0. -0. -0. -1.  1. -0. -0. -0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0. -0.
  -0. -0. -0. -0. -0. -0. -0. -0. -1.  1. -0. -0. -0. -0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  1. -0.
  -0. -0. -0. -0. -0. -0. -0. -1.  1. -0. -0. -0. -0. -0. -0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0. -0.
  -0. -0. -0. -0. -0. -0. -1.  1. -0. -0. -0. -0. -0. -0. -0. -0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1. -1.  0.  0. -0.
  -0. -1. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.  1.  1. -0. -0.]
 [ 0.  0.  0.

In [19]:
left_null_space_b = null_space(reversible_matrix.T)
left_null_space_b

array([], shape=(11, 0), dtype=float64)

(c). 

In [20]:
from sympy import symbols, Matrix

# Split the matrix into known and unknown parts
N_known = matrix[:, :7]  # First 7 columns for known rates
N_unknown = matrix[:, 7:]  # Remaining columns for unknown rates

print("N_known (matrix for known rates):")
print(N_known)

print("\nN_unknown (matrix for unknown rates):")
print(N_unknown)

N_known (matrix for known rates):
[[ 1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]]

N_unknown (matrix for unknown rates):
[[-1.  0.  0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0. -1.  0.  0.  1. -1.  0.  0.  0. -1.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  0.  1.]
 [ 1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  1.  1.]]


In [23]:
import numpy as np
from sympy import Matrix

# Define the stoichiometry matrix N
N = Matrix([
    [1, 0, 0, 0, -1, 0, 0, 1, -1, 0],
    [0, 1, 0, 0, 0, -1, 1, -1, 0, -1],
    [0, 0, -1, 0, 0, 0, 0, 0, 1, -1],
    [0, 0, 0, -1, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, -1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, -1, 0, 0, 1]
])

# Calculate the null space
null_space = N.nullspace()

# Display the null space basis vectors
print("Null space basis vectors (candidate flux modes):")
for vec in null_space:
    print(vec)

Null space basis vectors (candidate flux modes):
Matrix([[1], [0], [0], [0], [1], [1], [1], [0], [0], [0]])
Matrix([[-1], [1], [0], [0], [0], [0], [0], [1], [0], [0]])
Matrix([[1], [0], [1], [0], [0], [0], [0], [0], [1], [0]])
Matrix([[-1], [0], [-1], [1], [-1], [-1], [0], [0], [0], [1]])
