In [1]:
import numpy as np
import pandas as pd

In [23]:
matrix = np.zeros((11, 17))
matrix[0, 0] = 1
matrix[1, 1] = 1
matrix[6, 2] = 1
matrix[9, 3] = 1
matrix[7, 4] = -1
matrix[8, 5] = -1
matrix[10, 6] = -1

matrix[0, 7] = -1
matrix[5, 7] = 1

matrix[1, 8] = -1
matrix[4, 8] = 1
matrix[5, 8] = -1

matrix[3, 9] = 1
matrix[4, 9] = -1

matrix[2, 10] = 1
matrix[3, 10] = -1

matrix[1, 11] = 1
matrix[2, 11] = -1

matrix[0, 12] = 1
matrix[1, 12] = -1

matrix[0, 13] = -1
matrix[6, 13] = -1
matrix[7, 13] = 1
matrix[8, 13] = 1

matrix[6, 14] = -1
matrix[8, 14] = 1
matrix[9, 14] = 1
matrix[10, 14] = -1

matrix[9, 15] = -1
matrix[10, 15] = 1

matrix[1, 16] = -1
matrix[4, 16] = 1
matrix[8, 16] = -1
matrix[10, 16] = 1

print(matrix)

[[ 1.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0. -1.  0.  0.  1. -1.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1. -1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  1.  1.  0. -1.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0. -1.  1.  1.]]


In [24]:
from scipy.linalg import null_space

# Compute the left null space of the stoichiometry matrix
left_null_space = null_space(matrix.T)

# Check if the left null space is non-empty
if left_null_space.size == 0:
    print("There is no left nullspace.")
else:
    print("There is a left nullspace.")
    print("Left nullspace basis vectors:")
    print(left_null_space)

There is no left nullspace.


(b). 

In [25]:
from scipy.linalg import null_space

# Compute the null space of the matrix
kernel = null_space(matrix)

# Display the null space basis vectors
print("Kernel (null space) basis vectors:")
print(kernel)

Kernel (null space) basis vectors:
[[ 0.03017449 -0.41078298  0.57426224 -0.06669468 -0.0593047  -0.14467631]
 [-0.13957806  0.52875403 -0.02067784 -0.25749231  0.02975776  0.12411059]
 [-0.13998412  0.00434896  0.25203937  0.22411791  0.20247693  0.46293115]
 [-0.06818883 -0.09978943 -0.02998729 -0.36738989  0.44167385 -0.28050743]
 [-0.19620024 -0.11404556  0.2373946  -0.3056562  -0.03209489  0.30465104]
 [-0.45251144  0.09008786  0.3471825   0.22172803  0.18839506  0.04707142]
 [ 0.24433849 -0.18552832 -0.12513043 -0.36500001  0.45575572  0.1353523 ]
 [ 0.08679667  0.23201661  0.3161898  -0.0185308   0.00254794 -0.32521676]
 [ 0.08679667  0.23201661  0.3161898  -0.0185308   0.00254794 -0.32521676]
 [ 0.39932399  0.14627771  0.22104667 -0.01614092  0.01662981  0.09064297]
 [ 0.39932399  0.14627771  0.22104667 -0.01614092  0.01662981  0.09064297]
 [ 0.39932399  0.14627771  0.22104667 -0.01614092  0.01662981  0.09064297]
 [-0.13957806  0.52875403 -0.02067784 -0.25749231  0.02975776  0.

(c). 

In [26]:
from sympy import symbols, Matrix

# Split the matrix into known and unknown parts
N_known = matrix[:, :6]  # First 7 columns for known rates
N_unknown = matrix[:, 6:]  # Remaining columns for unknown rates

print("N_known (matrix for known rates):")
print(N_known)

print("\nN_unknown (matrix for unknown rates):")
print(N_unknown)

N_known (matrix for known rates):
[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]

N_unknown (matrix for unknown rates):
[[ 0. -1.  0.  0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  1. -1.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  1. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  1.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [-1.  0.  0.  0.  0.  0.  0.  0. -1.  1.  1.]]


In [27]:
from numpy.linalg import inv

# Compute the inverse of N_unknown
N_unknown_inv = inv(N_unknown)

# Display the inverse matrix
print("Inverse of N_unknown:")
print(N_unknown_inv)

Inverse of N_unknown:
[[-0. -0. -0. -0. -0. -0. -1. -0. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  0.  0. -1.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1.  0. -1.  0.  0.  0.]
 [-1. -1. -1. -1. -2. -1. -1. -1. -1.  0.  0.]
 [-1. -1. -1. -2. -2. -1. -1. -1. -1.  0.  0.]
 [-1. -1. -2. -2. -2. -1. -1. -1. -1. -0. -0.]
 [-0. -1. -1. -1. -1. -0. -0. -0. -0. -0. -0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1. -1.  0.  0.  0.]
 [-0. -0. -0. -0. -0. -0. -1. -1. -0. -1. -0.]
 [-0. -0. -0. -0. -0. -0. -1. -0. -1. -0. -0.]]
